CREATE TABLE 'comments_likes' (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	userID TEXT NOT NULL,
	messageID TEXT NOT NULL,
	like BOOL NOT NULL,
	UNIQUE (userID, messageID),
	FOREIGN KEY (userID) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (messageID) REFERENCES posts(id) ON DELETE CASCADE
);