CREATE TABLE  'chat_members' (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	chatID TEXT NOT NULL,
	userID TEXT NOT NULL,
	UNIQUE (chatID, userID),
	FOREIGN KEY (userID) REFERENCES 'users'(id) 
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
CREATE TABLE  'chat_messages' (
	id TEXT PRIMARY KEY NOT NULL,
	content TEXT NOT NULL,  
	images TEXT, 
	chat_membersID INTEGER NOT NULL,
	dateCreate TIMESTAMP NOT NULL,
	FOREIGN KEY (chat_membersID) REFERENCES 'chat_members'(id) 
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
		